---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}\
                  -{{ ansible_facts['distribution_major_version'] }}.yml"

- name: Install postfix packages
  ansible.builtin.package:
    name: "{{ postfix_packages }}"
    state: present

- name: Task postfix configuration
  ansible.builtin.import_tasks:
    file: configuration.yml
