---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}\
                        -{{ ansible_facts['distribution_major_version'] }}.yml"

- name: Install fail2ban packages
  ansible.builtin.package:
    name: "{{ fail2ban_packages }}"
    state: present

- name: Enable fail2ban server
  ansible.builtin.systemd:
    state: started
    name: "{{ fail2ban_service }}"
    enabled: true

- name: Configuration
  ansible.builtin.import_tasks:
    file: configure.yml
