---
- name: Get file stat of local {{ checkmk_agent_package }}
  ansible.builtin.stat:
    path: /tmp/{{ checkmk_agent_package }}
  check_mode: true
  delegate_to: localhost
  register: agent_file_local
  become: false

- name: Upload CheckMK agent package {{ checkmk_agent_version }}
  ansible.builtin.copy:
    src: /tmp/{{ checkmk_agent_package }}
    dest: /home/ansible/{{ checkmk_agent_package }}
    mode: u+rw,g+rw,o+rw
  when: agent_file_local.stat.exists

- name: Check that agent file exists {{ checkmk_agent_version }}
  ansible.builtin.stat:
    path: /home/ansible/{{ checkmk_agent_package }}
  check_mode: true
  register: agent_file

- name: Install CheckMK agent package {{ checkmk_agent_version }}
  ansible.builtin.apt:
    deb: "/home/ansible/{{ checkmk_agent_package }}"
  when:
    - ansible_facts['distribution'] == "Debian"
    - agent_file.stat.exists

- name: Remove remote CheckMK agent package file
  ansible.builtin.file:
    path: "/home/ansible/{{ checkmk_agent_package }}"
    state: absent

- name: Install time package
  ansible.builtin.apt:
    name: time
  when:
    - ansible_facts['distribution'] == "Debian"
